# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "activefacts-api"
  s.version = "0.8.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Clifford Heath"]
  s.date = "2012-01-03"
  s.description = "\nThe ActiveFacts API is a Ruby DSL for managing constellations of elementary facts.\nEach fact is either existential (a value or an entity), characteristic (boolean) or\nbinary relational (A rel B). Relational facts are consistently co-referenced, so you\ncan traverse them efficiently in any direction. Each constellation maintains constraints\nover the fact population.\n"
  s.email = "clifford.heath@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/activefacts/api.rb",
    "lib/activefacts/api/constellation.rb",
    "lib/activefacts/api/entity.rb",
    "lib/activefacts/api/instance.rb",
    "lib/activefacts/api/instance_index.rb",
    "lib/activefacts/api/numeric.rb",
    "lib/activefacts/api/object_type.rb",
    "lib/activefacts/api/role.rb",
    "lib/activefacts/api/role_values.rb",
    "lib/activefacts/api/standard_types.rb",
    "lib/activefacts/api/support.rb",
    "lib/activefacts/api/value.rb",
    "lib/activefacts/api/vocabulary.rb",
    "lib/activefacts/tracer.rb",
    "spec/autocounter_spec.rb",
    "spec/constellation_spec.rb",
    "spec/entity_type_spec.rb",
    "spec/identification_spec.rb",
    "spec/instance_spec.rb",
    "spec/role_values_spec.rb",
    "spec/roles_spec.rb",
    "spec/spec_helper.rb",
    "spec/value_type_spec.rb"
  ]
  s.homepage = "http://github.com/cjheath/activefacts-api"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A fact-based data model DSL and API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rdoc>, [">= 2.4.2"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rdoc>, [">= 2.4.2"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rdoc>, [">= 2.4.2"])
  end
end

